### ISSUE TITLE
Windows and MacOS compiled codec?

### ISSUE THREAD

**Issue by giant-void** [gopro/cineform-sdk#30]
Hey Cineform Team,

Is there a guide available for installing the latest compile of Cineform so we can get playback in our native OS's? 

Thanks,
Jonathan

**Comment by dnewman-gpsw** [comment]
The idea of native OS playback from third party codecs has been slowly obsoleted in recent years. Applications that use sandboxing can't use codecs via QuickTime, Directshow or other codec plugin APIs.  This is the reason we provide the CineForm SDK, so that application developer (and hopefully OSes) can add new codec support without using the intermediate (non-secure) media APIs.  Only the application, or OS developer, can do this work as codec installation is no longer a user enabled feature.
