### ISSUE TITLE
artifacts in samples

### ISSUE THREAD

**Issue by shekh** [gopro/cineform-sdk#7]
Saw it on samples from here: 
http://www.siliconimaging.com/DigitalCinema/Gallery/spider_8_22_Jul_2007_07_23_24.zip
See picture:
https://s1.postimg.org/5azx0o2tyn/frame-36.png

1. (marked blue): some smearing at the bottom. Not present when decoding with vfw codec 9.0.5
2. (marked red): vertical line, visible in RG24, BGRA decoding modes. Also present with vfw codec.

**Comment by olafmatt** [comment]
VfW plays the file at "half resolution". The artifact in (1.) looks like demosaicing with broken edge handling to me. Looking at the code there is a DECODED_RESOLUTION_HALF_NODEBAYER (and some other debayer options in decoder.h) which would probably give that half-resolution image (that you see in VfW) without running into the edge condition problem.

**Comment by shekh** [comment]
Also strange in this sample: encodedWidth/encodedHeight are 2048x1080 but in AVI header it is stored as 1024x540. Why is that?

**Comment by dnewman-gpsw** [comment]
Very early Silicon Imaging files had the wrong header information, as initially we didn't have a demosaic in the decoder -- it was in the Premiere Pro importer. The lower resolution in the header (DECODED_RESOLUTION_HALF_NODEBAYER) was so that VFW based thumbnail generation would work. We soon learned that adding the demosaic to the decoder was the best way forward. Also this early RAW example likely had the wrong wavelet edge filters -- very few of these images exist in the wild (from prototype SI-2K cameras.) Here is a RAW image we used for testing from 2009 http://miscdata.com/video/RAW1080p-I.avi

**Comment by shekh** [comment]
Thanks, so the issues resolve to poor/unsupported samples.
